language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "7.3"
    - php: "7.4"
    - php: "nightly"
  allow_failures:
    - php: "nightly"

install:
  - composer self-update
  - composer update
  - chmod +x bin/test-cli.sh

script:
  - composer test
  - bin/test-cli.sh
